-- Must have depencencies apt-get install postgresql-contrib
-- Must be run as superuser: CREATE EXTENSION hstore;

CREATE SCHEMA logloop;

CREATE TABLE logloop.events
(
  uuid uuid NOT NULL, -- Unique identifier of event. Ideally generated by logging application.
  "timestamp" timestamp with time zone NOT NULL DEFAULT now(), -- Times when evnet ocurred. Ideally set be logging application in @timestamp field.
  message text,
  fields hstore NOT NULL, -- Any additional fields from log event's JSON data. Contained fields differ per event.
  CONSTRAINT pk_uuid PRIMARY KEY (uuid)
);
COMMENT ON TABLE logloop.events
  IS 'Log events. Expected to remain empty as log are saved in daily child tables.';
COMMENT ON COLUMN logloop.events.uuid IS 'Unique identifier of event. Ideally generated by logging application.';
COMMENT ON COLUMN logloop.events."timestamp" IS 'Times when evnet ocurred. Ideally set be logging application in @timestamp field.';
COMMENT ON COLUMN logloop.events.fields IS 'Any additional fields from log event''s JSON data. Contained fields differ per event.';

CREATE TABLE logloop.events_schema
(
  name name NOT NULL, -- Name of events child relation.
  exclusive_upper_bound timestamp with time zone NOT NULL, -- Earliest time for which events are not contained in a child event relation.
  CONSTRAINT pk_name PRIMARY KEY (name)
);
COMMENT ON COLUMN logloop.events_schema.name IS 'Name of events child relation.';
COMMENT ON COLUMN logloop.events_schema.exclusive_upper_bound IS 'Earliest time for which events are not contained in a child event relation.';

CREATE OR REPLACE FUNCTION logloop.discard_older_than(days integer)
  RETURNS void AS
$BODY$
declare
	r record;
begin
	for r in select name
	from logloop.events_schema
	where exclusive_upper_bound<now()-(days||' day')::interval
	loop
		execute 'delete logloop.'||quote(r.name);
	end loop;
end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
COMMENT ON FUNCTION logloop.discard_older_than(integer) IS 'Deletes all event relations that do only contain events older than the given amount of days.';